/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.pr1;

import java.util.ArrayList;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        BookManager bookManager = new BookManager();
        try {
            bookManager.loadFromFile();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
