/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.pr1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

public class Main {

    private interface Command {
        public void excecute();
    }

    BookManager bookManager;
    Map<String, Command> commands = new HashMap<>();

    public Main () {
        bookManager = new BookManager();

        try {
            bookManager.loadFromFile();

        } catch (Exception e) {
            e.printStackTrace();
        }

        Command listAllBooks = () -> {
            bookManager.printBooks(bookManager.getBooks());
        };

        commands.put("list all books", listAllBooks);

    }
    public static void main(String[] args) {

        Main main = new Main();
        main.showAllOption();
    }

    public void showAllOption() {
        this.commands.keySet().forEach(action -> {
            System.out.println(action);
        });
    }
}
