/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.pr1;

import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

import main.java.pr1.commands.*;

public class Main {

    Map<Integer, Command> commands = new HashMap<>();

    public void addCommand (int commandId, Command command) {
        commands.put(commandId, command);
    }

    public void showAllOption() {
        System.out.println("-----------------------------------");

        commands.keySet().forEach(commandId -> {
            if (commandId != 0) {
                System.out.println(commandId + ". " + commands.get(commandId).getDescription());
            }
        });

        System.out.println("\n \n0. " + commands.get(0).getDescription());
        System.out.println("-----------------------------------");
    }

    public void excecuteOption(int commandId) {
        Command command = this.commands.get(commandId);
        if (command == null) {
            System.out.println("Invalid option!");
            return;
        }
        command.excecute();
    }

    public static void main(String[] args) {

        BookManager bookManager = new BookManager();        
        Main main = new Main();

        try {
            bookManager.loadFromFile();

        } catch (Exception e) {
            e.printStackTrace();
        }

        Scanner scanner = new Scanner(System.in);
        
        main.addCommand(0, new SaveAndExit(bookManager, scanner));
        main.addCommand(1, new ListAllBooks(bookManager));
        main.addCommand(2, new AddNewBook(bookManager, scanner));
        main.addCommand(3, new EditBook(bookManager, scanner));
        main.addCommand(4, new DeleteBook(bookManager, scanner));
        main.addCommand(5, new SearchBookByName(bookManager, scanner));
        main.addCommand(6, new SortBookByPriceDesc(bookManager));

        int id;
        do {
            main.showAllOption();

            System.out.print("Your option: ");
            id = scanner.nextInt(); 

            main.excecuteOption(id);

        } while (id != 0);
    }

}
